import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'pidgin' | 'yo' | 'ig' | 'ha';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        'landing.title': 'Which Lagos Area Fits You?',
        'landing.subtitle': 'Find the Lagos area that matches your lifestyle, budget, and vibe.',
        'landing.cta': 'Find Your Match',
        'landing.time': 'Takes 30 seconds • Data-backed',
        'landing.how.title': 'How it Works',
        'landing.how.subtitle': 'Get your perfect match in 3 easy steps',
        'landing.how.step1.title': 'Answer Questions',
        'landing.how.step1.text': 'Tell us about your budget, work location, and lifestyle.',
        'landing.how.step2.title': 'Get Matched',
        'landing.how.step2.text': 'Our algorithm finds the best areas for you instantly.',
        'landing.how.step3.title': 'Explore',
        'landing.how.step3.text': 'See detailed stats about your new potential home.',
        'landing.trending.title': 'Trending Areas',
        'landing.trending.subtitle': 'Top picks everyone is talking about this week.',
        'landing.trending.label': 'Trending',
        'landing.trending.starts': 'Starts from',
        'landing.view_history': 'View History',
        'nav.home': 'Home',
        'nav.how': 'How it Works',
        'nav.explore': 'Explore Areas',
        'nav.market': 'Market',
        'nav.about': 'About',
        'nav.pricing': 'Pricing',
        'nav.profile': 'My Profile',
        'nav.admin': 'Admin Panel',
        'nav.history': 'My History',
        'nav.signout': 'Sign Out',
        'nav.signin': 'Sign In',
        'nav.all_areas': 'All Areas',
        'nav.find_match': 'Find Your Match',
        'market.title.main': 'Accommodation Hub',
        'market.subtitle.main': "Found your area? Now let's find your home. Search platforms, connect with agents, and browse verified listings.",
        'market.select_area': 'Select Area',
        'market.search_placeholder': 'Search areas...',
        'market.searching_in': 'Currently Searching In',
        'market.search_btn': 'Search',
        'market.safety.title': 'Agent Tips & Safety',
        'market.safety.subtitle': 'How to navigate the Lagos rental market safely.',
        'market.safety.tip1.title': 'Verify Before Pay',
        'market.safety.tip1.text': "Never pay for an apartment you haven't physically inspected. Scams are common online.",
        'market.safety.tip2.title': 'Ask for the Landlord',
        'market.safety.tip2.text': 'Ensure the agent is authorized. Request to see the caretaker or landlord when finalized.',
        'market.safety.tip3.title': 'Check Different Platforms',
        'market.safety.tip3.text': 'The same apartment can be listed on multiple platforms with different prices. Always compare.',
        'market.directory.title': 'Agent & Agency Directory',
        'market.directory.subtitle': 'Verified real estate agents, rated agencies, office locations, and social media handles — all in one place.',
        'market.platform.propertypro.desc': 'One of the largest property search platforms in Africa.',
        'market.platform.naijahouses.desc': 'Comprehensive Lagos listings with verified properties.',
        'market.platform.myplace.desc': 'Modern property search with diverse Lagos options.',
        'market.platform.listproperty.desc': 'Trusted portal for finding your next Lagos home.',
        'market.platform.marketplace.desc': 'Direct connections to verified agents and listings.',
        'market.platform.tiktok.desc': 'Watch real-time house tours and agent walkthroughs.',
        'market.tip.social': 'TIP: Search for these property types on TikTok & Instagram',
        'market.tabs.platforms': 'Platforms',
        'market.tabs.agents': 'Verified Agents',
        'market.category.individual': 'Agents',
        'market.category.agencies': 'Agencies',
        'market.category.offices': 'Offices',
        'market.category.social': 'Social',
        'market.verified': 'Verified Agent',
        'market.loading': 'Loading agents...',
        'market.call': 'Call Agency',
        'market.website': 'Website',
        'market.whatsapp': 'WhatsApp Chat',
        'market.premium.title': 'Upgrade to Premium',
        'market.premium.text': 'Unlock verified agents, agencies, and TikTok handles to find your perfect Lagos apartment.',
        'market.premium.btn': 'Activate Pro Access',
        'market.premium.success.title': 'Welcome to Premium!',
        'market.premium.success.text': 'You now have full access to our verified agent directory, agencies, and all premium features.',
        'market.premium.success.btn': 'Explore Agents Now',
        'budget.title': 'Lagos on a Budget',
        'budget.subtitle': 'Curated budget-friendly outings in Lagos. From under 5k to 30k — handpicked from trending TikTok & IG reels.',
        'budget.category.all': 'All Budgets',
        'budget.category.under_5k': 'Under ₦5k',
        'budget.category.under_15k': 'Under ₦15k',
        'budget.category.under_20k': 'Under ₦20k',
        'budget.category.under_30k': 'Under ₦30k',
        'budget.source_by': 'Handpicked by {0}',
        'budget.pro_tag': 'PRO FEATURE',
        'market.tabs.budget': 'Budget Outings',
        'property.type.self_contain': 'Self Contain',
        'property.type.single_room': 'Single Room',
        'property.type.flat_1': '1 Bedroom Flat',
        'property.type.flat_2': '2 Bedroom Flat',
        'property.type.flat_3': '3 Bedroom Flat',
        'property.type.duplex': 'Duplex',
        'property.type.shared': 'Shared Apartment',
        'quiz.progress': 'Question {0} of {1}',
        'quiz.multi_select': 'Multi-select enabled',
        'quiz.budget_label': 'Or type your annual budget (₦):',
        'quiz.budget_placeholder': 'e.g. 1,500,000',
        'quiz.next': 'Next',
        'quiz.back': 'Back',
        'quiz.results': 'See Results',
        'result.based_on': 'Based on your answers',
        'result.perfect_match': 'We Found Your Perfect Match',
        'result.top_rec': 'TOP RECOMMENDATION',
        'result.specific_spots': 'Try these specific spots:',
        'result.rent': 'Rent',
        'result.noise': 'Noise',
        'result.lifestyle': 'Lifestyle',
        'result.power': 'Power',
        'result.street_talk': 'Street Talk',
        'result.trending': 'TRENDING',
        'result.complaints': 'Complaints',
        'result.compliments': 'Compliments',
        'result.explore_btn': 'Explore {0}',
        'result.find_apt': 'Find an Apartment',
        'result.neighbors': 'Closest Neighbors',
        'result.other_options': 'Other great options',
        'result.retake': 'Retake Quiz',
        'result.no_match_title': 'Budget Reality Check',
        'explore.title': 'Explore Lagos Areas',
        'explore.subtitle': 'Discover detailed insights about every neighborhood.',
        'explore.search_placeholder': 'Search for an area (e.g. Yaba, Lekki)...',
        'explore.sort.alpha_asc': 'Alphabetical (A-Z)',
        'explore.sort.alpha_desc': 'Alphabetical (Z-A)',
        'explore.sort.price_asc': 'Price (Low to High)',
        'explore.sort.price_desc': 'Price (High to Low)',
        'explore.avg_rent': 'Avg. Rent',
        'explore.experience_title': 'Experience Lagos',
        'explore.experience_subtitle': 'Curated lists of where to go and what to eat.',
        'explore.visit_title': 'Places You Need to Visit',
        'explore.eat_title': 'What to Eat',
        'explore.details.price_range': 'Price Range',
        'explore.details.vibe': 'Vibe / Noise',
        'explore.details.commute': 'Estimated Commute (Driving)',
        'explore.details.to_vi': 'To Victoria Island',
        'explore.details.to_ikeja': 'To Ikeja (Central)',
        'explore.details.localities': 'Inner Localities & Areas',
        'explore.details.hotspots': 'Popular Hotspots',
        'explore.details.proximity': 'Proximity to Other Areas',
        'explore.details.distance_note': '*Distances are approximate "as the crow flies".',
        'explore.details.ready_title': 'Ready to move to {0}?',
        'explore.details.ready_text': 'Connect with verified agents and browse available apartments in {0} right now.',
        'explore.details.find_btn': 'Find an Apartment',
        'explore.details.quiz_note': 'Does this sound like you? {0} to be sure!',
        'explore.details.take_quiz': 'Take the quiz',
        'explore.details.street_talk': 'STREET TALK',
        'explore.details.local_perks': 'LOCAL PERKS',
        'explore.details.mapping_note': "We're still mapping the best spots in {0}. Check back soon for food and sport recommendations!",
        'about.title': 'About LagosFit',
        'about.subtitle': 'Helping you find your place in the chaos and charm of Lagos.',
        'about.story_title': 'Our Story',
        'about.story_text': 'Lagos is vibrant, fast-paced, and sometimes overwhelming. With over 20 million people and dozens of unique neighborhoods, finding the right place to call home is a challenge. LagosFit was born out of a simple idea: What if you could find your perfect neighborhood in just 30 seconds? We combine data on rent, commute times, and lifestyle vibes to match you with your ideal Lagos area.',
        'about.values_title': 'Why We Do This',
        'about.value1_title': 'Empowerment',
        'about.value1_text': 'Giving you the info you need to make smart housing decisions.',
        'about.value2_title': 'Authenticity',
        'about.value2_text': 'Real data about real Lagos areas. No sugar-coating.',
        'about.value3_title': 'Simplicity',
        'about.value3_text': "House hunting is hard. This quiz shouldn't be.",
        'about.contact_title': 'Get in Touch',
        'about.contact_text': 'Have suggestions or just want to say hello? drop us a message.',
        'about.contact_btn': 'Contact Us',
        'footer.tagline': 'The smart way to find your perfect neighborhood in Lagos. Data-driven, honest, and easy.',
        'footer.explore': 'Explore',
        'footer.company': 'Company',
        'footer.connect': 'Connect',
        'footer.contact': 'Contact',
        'footer.privacy': 'Privacy Policy',
        'footer.built_for': 'Built for Lagos.',
        'review.title': 'User Reviews',
        'review.share_exp': 'Share Your Experience',
        'review.pro_only': 'Only Pro members can leave reviews. Upgrade to help the community with your insights!',
        'review.upgrade_btn': 'Upgrade to Pro',
        'review.your_rating': 'Your Rating',
        'review.your_comment': 'Your Comment',
        'review.placeholder': "What's it like living here? Describe the vibe, safety, and amenities...",
        'review.submitted': 'Review submitted!',
        'review.post_btn': 'Post Review',
        'review.submitting': 'Submitting...',
        'review.loading': 'Loading reviews...',
        'review.no_reviews': 'No reviews yet. Be the first to share your thoughts!',
        'auth.login_title': 'Welcome Back',
        'auth.login_subtitle': 'Ready to find your perfect Lagos neighborhood?',
        'auth.google_btn': 'Continue with Google',
        'auth.or_email': 'or sign in with email',
        'auth.email_label': 'Email Address',
        'auth.password_label': 'Password',
        'auth.name_label': 'Full Name',
        'auth.login_btn': 'Sign In',
        'auth.register_title': 'Create Account',
        'auth.register_subtitle': 'Join LagosFit to save your search history and more.',
        'auth.register_btn': 'Create Account',
        'auth.forgot_password': 'Forgot your password?',
        'auth.no_account': "Don't have an account?",
        'auth.register_link': 'Register here',
        'auth.have_account': 'Already have an account?',
        'auth.login_link': 'Sign in instead',
        'auth.forgot_title': 'Reset Password',
        'auth.forgot_subtitle': "Enter your email and we'll send you a reset link.",
        'auth.reset_btn': 'Send Reset Link',
        'auth.back_to_login': 'Back to Login',
        'auth.reset_success': 'Reset link sent! Check your email.',
        'auth.reset_check_email': 'Check Your Email',
        'auth.reset_sent_to': 'We sent a password reset link to {0}.',
        'auth.reset_instruction': 'Click the link in the email to reset your password.',
        'auth.reset_not_received': "Didn't get it?",
        'auth.reset_spam_note': 'Check your spam folder or',
        'auth.reset_try_again': 'try again',
        'auth.error.user_not_found': 'No account found with this email.',
        'auth.error.wrong_password': 'Incorrect password. Try again.',
        'auth.error.invalid_credential': 'Invalid email or password.',
        'auth.error.too_many_requests': 'Too many attempts. Please wait a bit.',
        'auth.error.popup_closed': 'Sign-in popup was closed. Try again.',
        'auth.error.network_failed': 'Network error. Check your connection.',
        'auth.error.generic': 'Sign-in failed. Please try again.',
        'auth.error.email_in_use': 'An account with this email already exists.',
        'auth.error.weak_password': 'Password must be at least 6 characters.',
        'auth.error.invalid_email': 'Please enter a valid email address.',
        'auth.error.passwords_dont_match': 'Passwords do not match.',
        'pricing.title': 'Simple, Transparent Pricing',
        'pricing.subtitle': 'Join 5,000+ users finding their perfect home with data-backed insights.',
        'pricing.badge': 'LEVEL UP YOUR SEARCH',
        'pricing.monthly': 'Monthly',
        'pricing.yearly': 'Yearly',
        'pricing.free_name': 'Explorer',
        'pricing.free_desc': 'For occasional browsers.',
        'pricing.free_price': '₦0',
        'pricing.forever': '/ forever',
        'pricing.pro_name': 'LagosFit Pro',
        'pricing.pro_desc': 'For serious home seekers.',
        'pricing.popular': 'POPULAR',
        'pricing.per_period': '/ {0}',
        'pricing.current_plan': 'Current Plan',
        'pricing.get_started': 'Get Started',
        'pricing.already_pro': 'Already Pro',
        'pricing.upgrade_btn': 'Upgrade to Pro',
        'pricing.secure_payment': 'Secure Payment',
        'pricing.via_paystack': 'Via Paystack',
        'pricing.instant_activation': 'Instant Activation',
        'pricing.unlock_pro': 'Unlock pro features now',
        'pricing.feat1': 'Access to Property Platforms',
        'pricing.feat2': 'Verified agents with direct contacts',
        'pricing.feat3': 'Rated agencies with websites & emails',
        'pricing.feat4': 'Office locations across Lagos',
        'pricing.feat5': 'TikTok handles for property tours',
        'pricing.feat6': 'WhatsApp direct chat links',
        'profile.title': 'Your Profile',
        'profile.edit_btn': 'Edit Profile',
        'profile.save_btn': 'Save',
        'profile.saving': 'Saving...',
        'profile.cancel': 'Cancel',
        'profile.name_label': 'Display Name',
        'profile.name_placeholder': 'Full Name',
        'profile.set_name': 'Set your name',
        'profile.updated_success': 'Profile updated successfully!',
        'profile.updated_fail': 'Failed to update profile.',
        'profile.avatar_updated': 'Profile picture updated!',
        'profile.avatar_optimizing': 'Optimizing image...',
        'profile.avatar_saving': 'Saving to your profile...',
        'profile.shortlist_title': 'Your Shortlist',
        'profile.no_favorites': "You haven't saved any areas yet.",
        'profile.explore_btn': 'Explore Areas',
        'profile.preferences': 'Preferences',
        'profile.alerts': 'Price Alerts (Shortlist)',
        'profile.summary': 'Weekly Market Summary',
        'profile.recent_quiz': 'Recent Quiz',
        'profile.view_all': 'View All',
        'profile.no_history': 'No quiz history yet.',
        'profile.take_quiz': 'Take Quiz',
        'profile.latest_rec': 'Latest Recommendation',
        'profile.review_result': 'Re-view Full Result',
        'profile.pro_badge': 'PRO',
        'profile.upgrade_title': 'Upgrade to Pro',
        'profile.upgrade_desc': 'Get neighborhood reports, safety stats, and agent contacts.',
        'profile.view_pricing': 'View Pricing',
        'history.title': 'Your Search History',
        'history.subtitle': 'Revisit your previous quiz results and recommendations.',
        'history.no_history': 'No history found. Take the quiz to get started!',
        'history.back_to_profile': 'Back to Profile',
        'buddy.welcome': "Kedu! (Hello!) I'm Buddy, your LagosFit assistant. I know Lagos like the back of my hand. Ask me about house prices in Lekki, the best vibes in Ikeja, or how to get a verified agent!"
    },
    pidgin: {
        'landing.title': 'Which Lagos Area Fit You?',
        'landing.subtitle': 'Find the area wey align with your pocket and lifestyle.',
        'landing.cta': 'Find Your Match Now!',
        'landing.time': 'E no go pass 30 seconds',
        'landing.how.title': 'How E Dey Work',
        'landing.how.subtitle': 'Get your perfect area in 3 easy steps',
        'landing.how.step1.title': 'Answer Question',
        'landing.how.step1.text': 'Tell us about your pocket, where you dey work, and your lifestyle.',
        'landing.how.step2.title': 'Get Match',
        'landing.how.step2.text': 'Our system go find the area wey set for you sharply.',
        'landing.how.step3.title': 'Check Am Out',
        'landing.how.step3.text': 'See all the gist about your new potential area.',
        'landing.trending.title': 'Areas Wey Dey Blow',
        'landing.trending.subtitle': 'The hot picks wey everybody dey talk about this week.',
        'landing.trending.label': 'Dey Blow',
        'landing.trending.starts': 'E start from',
        'landing.view_history': 'See History',
        'nav.home': 'House',
        'nav.how': 'How E Dey Work',
        'nav.explore': 'See Areas',
        'nav.market': 'Market',
        'nav.about': 'About Us',
        'nav.pricing': 'Price List',
        'nav.profile': 'My Profile',
        'nav.admin': 'Admin Panel',
        'nav.history': 'My History',
        'nav.signout': 'Sign Out',
        'nav.signin': 'Sign In',
        'nav.all_areas': 'Check Every Area',
        'nav.find_match': 'Find Your Correct Area',
        'market.title.main': 'Accommodation Hub',
        'market.subtitle.main': 'You don find area? Now make we find house. Check platforms, follow agents talk, and see verified house listings.',
        'market.select_area': 'Select Area',
        'market.search_placeholder': 'Find area...',
        'market.searching_in': 'We dey search for',
        'market.search_btn': 'Search',
        'market.safety.title': 'Agent Gist & Safety',
        'market.safety.subtitle': 'How to find house for Lagos without stress or wahala.',
        'market.safety.tip1.title': 'Check Am Well Before Pay',
        'market.safety.tip1.text': 'No ever pay for house wey you never see with your two eyes. People over dey ripper online.',
        'market.safety.tip2.title': 'Ask for the Landlord',
        'market.safety.tip2.text': 'Make sure say the agent na original. Ask to see the landlord or caretaker before you pay.',
        'market.safety.tip3.title': 'Check Other Places',
        'market.safety.tip3.text': 'The same house fit get different prices for different places. Check well make you for know the correct one.',
        'market.directory.title': 'Agent & Agency Directory',
        'market.directory.subtitle': 'Verified agents, big agencies, office address, and TikTok handles — everything for one place.',
        'market.platform.propertypro.desc': 'One of the biggest platforms to find house for Africa.',
        'market.platform.naijahouses.desc': 'Correct Lagos listings with verified properties.',
        'market.platform.myplace.desc': 'Modern way to search for different Lagos areas.',
        'market.platform.listproperty.desc': 'The portal wey you fit trust to find your next Lagos home.',
        'market.platform.marketplace.desc': 'Direct follow original agents and listings talk.',
        'market.platform.tiktok.desc': 'Watch real house tours and agent walkthrough as e dey happen.',
        'market.tip.social': 'TIP: Search for these house types for TikTok & Instagram',
        'market.tabs.platforms': 'Platforms',
        'market.tabs.agents': 'Verified Agents',
        'market.category.individual': 'Agents',
        'market.category.agencies': 'Agencies',
        'market.category.offices': 'Offices',
        'market.category.social': 'Social',
        'market.verified': 'Verify Agent',
        'market.loading': 'We dey find agents...',
        'market.call': 'Call Agent',
        'market.website': 'Website',
        'market.whatsapp': 'WhatsApp Chat',
        'market.premium.title': 'Upgrade to Premium',
        'market.premium.text': 'Unlock agents, agencies, and TikTok handles wey we don verify to find your house.',
        'market.premium.btn': 'Activate Pro Access',
        'market.premium.success.title': 'Welcome to Premium!',
        'market.premium.success.text': 'You now get full access to our original agents, agencies, and extra features.',
        'market.premium.success.btn': 'Check Agents Now',
        'budget.title': 'Lagos on a Budget',
        'budget.subtitle': 'Beta outings for Lagos wey no go break your bank. From 5k reach 30k — as seen for TikTok & Instagram.',
        'budget.category.all': 'Every Budget',
        'budget.category.under_5k': 'Under ₦5k',
        'budget.category.under_15k': 'Under ₦15k',
        'budget.category.under_20k': 'Under ₦20k',
        'budget.category.under_30k': 'Under ₦30k',
        'budget.source_by': 'Na {0} pick am',
        'budget.pro_tag': 'PRO FEATURE',
        'market.tabs.budget': 'Beta Outings',
        'property.type.self_contain': 'Self Contain',
        'property.type.single_room': 'Single Room',
        'property.type.flat_1': '1 Bedroom Flat',
        'property.type.flat_2': '2 Bedroom Flat',
        'property.type.flat_3': '3 Bedroom Flat',
        'property.type.duplex': 'Duplex',
        'property.type.shared': 'Shared Apartment',
        'quiz.progress': 'Question {0} of {1}',
        'quiz.multi_select': 'You fit pick many',
        'quiz.budget_label': 'Or type how much you wan pay per year (₦):',
        'quiz.budget_placeholder': 'e.g. 1,500,000',
        'quiz.next': 'Go Front',
        'quiz.back': 'Go Back',
        'quiz.results': 'Check Result',
        'result.based_on': 'Based on your answers',
        'result.perfect_match': 'We Don Find Your Correct House',
        'result.top_rec': 'NUMBER ONE CHOICE',
        'result.specific_spots': 'Check these areas well:',
        'result.rent': 'Rent',
        'result.noise': 'Noise',
        'result.lifestyle': 'Lifestyle',
        'result.power': 'Power',
        'result.street_talk': 'Street Talk',
        'result.trending': 'HOT CAKE',
        'result.complaints': 'Wetyn people no like',
        'result.compliments': 'Wetyn people like',
        'result.explore_btn': 'Look inside {0}',
        'result.find_apt': 'Find Apartment',
        'result.neighbors': 'Areas wey near',
        'result.other_options': 'Other better choices',
        'result.retake': 'Do Quiz Again',
        'result.no_match_title': 'Budget Reality Check',
        'explore.title': 'Explore Lagos Areas',
        'explore.subtitle': 'Check everything about every area inside Lagos.',
        'explore.search_placeholder': 'Find area (e.g. Yaba, Lekki)...',
        'explore.sort.alpha_asc': 'Alphabetical (A-Z)',
        'explore.sort.alpha_desc': 'Alphabetical (Z-A)',
        'explore.sort.price_asc': 'Price (Low to High)',
        'explore.sort.price_desc': 'Price (High to Low)',
        'explore.avg_rent': 'Normal Rent',
        'explore.experience_title': 'Experience Lagos',
        'explore.experience_subtitle': 'Correct lists of where to go and wetyn to chop.',
        'explore.visit_title': 'Places Wey You Must Visit',
        'explore.eat_title': 'Wetyn to Chop',
        'explore.details.price_range': 'How Much E Dey Be',
        'explore.details.vibe': 'Vibe / Noise',
        'explore.details.commute': 'How long e go take (Driving)',
        'explore.details.to_vi': 'To Victoria Island',
        'explore.details.to_ikeja': 'To Ikeja (Central)',
        'explore.details.localities': 'Inner Localities & Areas',
        'explore.details.hotspots': 'Beta Hotspots',
        'explore.details.proximity': 'Areas Wey Near',
        'explore.details.distance_note': '*Distances na approximate "as the crow flies".',
        'explore.details.ready_title': 'You don ready to move to {0}?',
        'explore.details.ready_text': 'Follow verified agents talk well and see correct apartments for {0} now.',
        'explore.details.find_btn': 'Find Apartment',
        'explore.details.quiz_note': 'This one set for you? {0} make you verify!',
        'explore.details.take_quiz': 'Do the quiz',
        'explore.details.street_talk': 'STREET TALK',
        'explore.details.local_perks': 'LOCAL PERKS',
        'explore.details.mapping_note': "We still dey map the best spots for {0}. Check back soon for food and sport gist!",
        'about.title': 'About LagosFit',
        'about.subtitle': 'We dey help you find your corner inside the sweet wahala/enjoyment of Lagos.',
        'about.story_title': 'Who We Be?',
        'about.story_text': 'Lagos logic no be for everybody. E big, e busy, and sometimes e dey turn person eye. With plenti people and area wey different, finding house na serious work. Na why we create LagosFit: make you fit know where conform for you inside 30 seconds. We look rent money, waka distance, and how the area be generally to tell you true.',
        'about.values_title': 'Why We Dey Run Am',
        'about.value1_title': 'We Dey For You',
        'about.value1_text': "We wan give you correct info make you no enter 'one chance' for house matter.",
        'about.value2_title': 'No Film Trick',
        'about.value2_text': 'Real gist about Lagos areas. As e dey be, na im we talk.',
        'about.value3_title': 'No Stress',
        'about.value3_text': 'Looking for house hard enough. This quiz suppose dey easy.',
        'about.contact_title': 'Holla At Us',
        'about.contact_text': 'You get gist, advice, or you just wan greet? Send us mail.',
        'about.contact_btn': 'Send Mail',
        'footer.tagline': 'The beta way to find your correct area for Lagos. No film trick, just reality.',
        'footer.explore': 'See Areas',
        'footer.company': 'Company',
        'footer.connect': 'Connect',
        'footer.contact': 'Contact Us',
        'footer.privacy': 'Privacy Policy',
        'footer.built_for': 'Lagos Product.',
        'review.title': 'User Reviews',
        'review.share_exp': 'Tell Us How E Be',
        'review.pro_only': 'Only Pro members fit drop review. Upgrade make you help others find beta area!',
        'review.upgrade_btn': 'Upgrade to Pro',
        'review.your_rating': 'Your Rating',
        'review.your_comment': 'Your Comment',
        'review.placeholder': 'How this area be? Talk about the vibe, light, and safety...',
        'review.submitted': 'Review don enter!',
        'review.post_btn': 'Post Review',
        'review.submitting': 'Hold on...',
        'review.loading': 'Wait small...',
        'review.no_reviews': 'No reviews yet. Be the first to talk wetyn you know!',
        'auth.login_title': 'Welcome Back',
        'auth.login_subtitle': 'You don ready to find area wey conform for you?',
        'auth.google_btn': 'Follow Google enter',
        'auth.or_email': 'or use email sign in',
        'auth.email_label': 'Email Address',
        'auth.password_label': 'Password',
        'auth.name_label': 'Your Full Name',
        'auth.login_btn': 'Sign In',
        'auth.register_title': 'Create Account',
        'auth.register_subtitle': 'Join us make you fit save your area search history.',
        'auth.register_btn': 'Create Account',
        'auth.forgot_password': 'You don forget password?',
        'auth.no_account': 'You never get account?',
        'auth.register_link': 'Register here',
        'auth.have_account': 'You don get account before?',
        'auth.login_link': 'Sign in instead',
        'auth.forgot_title': 'Reset Password',
        'auth.forgot_subtitle': 'Put your email make we send you reset link.',
        'auth.reset_btn': 'Send Reset Link',
        'auth.back_to_login': 'Go back to Login',
        'auth.reset_success': 'Reset link don land! Check your mail.',
        'auth.reset_check_email': 'Check Your Email',
        'auth.reset_sent_to': 'We sent a password reset link to {0}.',
        'auth.reset_instruction': 'Click the link in the email to reset your password.',
        'auth.reset_not_received': "You no see am?",
        'auth.reset_spam_note': 'Check your spam folder or',
        'auth.reset_try_again': 'try again',
        'auth.error.user_not_found': 'We no find account for this email.',
        'auth.error.wrong_password': 'Password no correct. Try again.',
        'auth.error.invalid_credential': 'Email or password no correct.',
        'auth.error.too_many_requests': 'You don try too much. Wait small.',
        'auth.error.popup_closed': 'You close the popup. Refresh and try again.',
        'auth.error.network_failed': 'Network issue. Check your data.',
        'auth.error.generic': 'Sign-in no work. Check well and try again.',
        'auth.error.email_in_use': 'Account with this email already dey.',
        'auth.error.weak_password': 'Password must be reach 6 characters.',
        'auth.error.invalid_email': 'Put correct email address.',
        'auth.error.passwords_dont_match': 'Passwords no match.',
        'pricing.title': 'Better Price wey Clear',
        'pricing.subtitle': 'Join over 5,000 people wey don find house for here.',
        'pricing.badge': 'LEVEL UP YOUR SEARCH',
        'pricing.monthly': 'Every Month',
        'pricing.yearly': 'Every Year',
        'pricing.free_name': 'Explorer',
        'pricing.free_desc': 'For people wey just dey look.',
        'pricing.free_price': '₦0',
        'pricing.forever': '/ forever',
        'pricing.pro_name': 'LagosFit Pro',
        'pricing.pro_desc': 'For people wey really wan find house.',
        'pricing.popular': 'POPULAR',
        'pricing.per_period': '/ {0}',
        'pricing.current_plan': 'Your Plan',
        'pricing.get_started': 'Start Now',
        'pricing.already_pro': 'You be Pro already',
        'pricing.upgrade_btn': 'Upgrade to Pro',
        'pricing.secure_payment': 'Secure Payment',
        'pricing.via_paystack': 'Follow Paystack',
        'pricing.instant_activation': 'Quick Activation',
        'pricing.unlock_pro': 'Open pro features now',
        'pricing.feat1': 'See all property platforms',
        'pricing.feat2': 'Correct agents wey you fit call',
        'pricing.feat3': 'Agencies with clean website',
        'pricing.feat4': 'Office for inside Lagos',
        'pricing.feat5': 'TikTok link for house tour',
        'pricing.feat6': 'WhatsApp chat link',
        'profile.title': 'Your Profile',
        'profile.edit_btn': 'Change Profile',
        'profile.save_btn': 'Save am',
        'profile.saving': 'E dey save...',
        'profile.cancel': 'Comot',
        'profile.name_label': 'Your Name',
        'profile.name_placeholder': 'Full Name',
        'profile.set_name': 'Put your name',
        'profile.updated_success': 'Profile don change well!',
        'profile.updated_fail': 'Profile update fail.',
        'profile.avatar_updated': 'Profile picture don change!',
        'profile.avatar_optimizing': 'E dey fix image...',
        'profile.avatar_saving': 'E dey save picture...',
        'profile.shortlist_title': 'Area wey you like',
        'profile.no_favorites': 'You never save any area.',
        'profile.explore_btn': 'Check Areas',
        'profile.preferences': 'Settings',
        'profile.alerts': 'Price Alerts',
        'profile.summary': 'Weekly Market Update',
        'profile.recent_quiz': 'Last Quiz',
        'profile.view_all': 'See All',
        'profile.no_history': 'No quiz history dey.',
        'profile.take_quiz': 'Start Quiz',
        'profile.latest_rec': 'Last Area wey we show you',
        'profile.review_result': 'See full result again',
        'profile.pro_badge': 'PRO',
        'profile.upgrade_title': 'Upgrade to Pro',
        'profile.upgrade_desc': 'See deep reports and agents wey you fit call.',
        'profile.view_pricing': 'Check Price',
        'history.title': 'Your Search History',
        'history.subtitle': 'Check all your previous house search results.',
        'history.no_history': 'No history. Take the quiz to see area!',
        'history.back_to_profile': 'Go back to Profile',
        'buddy.welcome': "Oshey! I be Buddy, your LagosFit expert. I sabi Lagos well well. Ask me anything about house for Lekki, cool spots for Ikeja, or how you fit find original agents!"
    },
    yo: {
        'landing.title': 'Ibugbe Lagos wo lo tọ si ọ?',
        'landing.subtitle': 'Wa agbegbe Lagos ti o ba igbesi aye, eto isuna, ati ifẹ rẹ mu.',
        'landing.cta': 'Wa Ibamu Rẹ',
        'landing.time': 'Iṣẹju 30 ni o n gba • Atilẹyin nipasẹ data',
        'landing.how.title': 'Bawo ni o ṣe n ṣiṣẹ',
        'landing.how.subtitle': 'Gba ibamu pipe rẹ ni awọn igbesẹ 3 rọrun',
        'landing.how.step1.title': 'Idahun Awọn ibeere',
        'landing.how.step1.text': 'Sọ fun wa nipa isuna rẹ, ipo iṣẹ, ati igbesi aye rẹ.',
        'landing.how.step2.title': 'Gba Ibamu',
        'landing.how.step2.text': 'Algoridimu wa wa awọn agbegbe ti o dara julọ fun ọ lẹsẹkẹsẹ.',
        'landing.how.step3.title': 'Ṣawari',
        'landing.how.step3.text': 'Wo awọn iṣiro alaye nipa ile tuntun rẹ ti o le jẹ.',
        'landing.trending.title': 'Awọn Agbegbe Ti Nṣiṣẹ',
        'landing.trending.subtitle': 'Awọn yiyan oke ti gbogbo eniyan n sọrọ nipa ọsẹ yii.',
        'landing.trending.label': 'Nṣiṣẹ',
        'landing.trending.starts': 'Bẹrẹ lati',
        'landing.view_history': 'Wo Itan',
        'nav.home': 'Ile',
        'nav.how': 'Bii o ti n ṣiṣẹ',
        'nav.explore': 'Ṣawari Awọn Agbegbe',
        'nav.market': 'Ọja',
        'nav.about': 'Nipa Wa',
        'nav.pricing': 'Iye Owo',
        'nav.profile': 'Profaili Mi',
        'nav.admin': 'Igbimọ Isakoso',
        'nav.history': 'Itan Mi',
        'nav.signout': 'Jade',
        'nav.signin': 'Wọle',
        'nav.all_areas': 'Gbogbo Agbegbe',
        'nav.find_match': 'Wa Ibugbe Rẹ',
        'market.title.main': 'Ibugbe Ibugbe',
        'market.subtitle.main': 'Njẹ o ti wa agbegbe rẹ bi? Bayi jẹ ki a wa ile rẹ. Ṣawari awọn iru ẹrọ, sopọ pẹlu awọn aṣoju, ati ṣawari awọn atokọ ti o jẹrisi.',
        'market.select_area': 'Yan Agbegbe',
        'market.search_placeholder': 'Ṣawari awọn agbegbe...',
        'market.searching_in': 'Lọwọlọwọ Nṣawari Ni',
        'market.search_btn': 'Wa',
        'market.safety.title': 'Awọn imọran Aṣoju & Aabo',
        'market.safety.subtitle': 'Bi o ṣe le lilö kiri ni ọja iyalo Lagos lailewu.',
        'market.safety.tip1.title': 'Daju Ṣaaju Sanwo',
        'market.safety.tip1.text': 'Ma ṣe sanwo fun iyẹwu ti o ko ti ṣayẹwo tikararẹ. Awọn itanjẹ jẹ wọpọ lori ayelujara.',
        'market.safety.tip2.title': 'Beere fun Olile',
        'market.safety.tip2.text': 'Rii daju pe aṣoju ti ni aṣẹ. Beere lati ri olutọju tabi onile nigbati o ba pari.',
        'market.safety.tip3.title': 'Ṣayẹwo Awọn oriṣiriṣi Awọn iru ẹrọ',
        'market.safety.tip3.text': 'Iyẹwu kanna ni a le ṣe atokọ lori awọn iru ẹrọ lọpọlọpọ pẹlu awọn idiyele oriṣiriṣi. Nigbagbogbo ṣe afiwe.',
        'market.directory.title': 'Itọsọna Aṣoju & Ile-iṣẹ',
        'market.directory.subtitle': 'Awọn aṣoju ohun-ini gidi ti a fọwọsi, awọn ile-iṣẹ ti a ṣe iwọn, ati awọn kapa media awujọ — gbogbo rẹ ni aye kan.',
        'market.platform.propertypro.desc': 'Ọkan ninu awọn iru ẹrọ wiwa ohun-ini ti o tobi julọ ni Afirika.',
        'market.platform.naijahouses.desc': 'Awọn atokọ Lagos okeerẹ pẹlu awọn ohun-ini ti o jẹrisi.',
        'market.platform.myplace.desc': 'Wiwa ohun-ini ode oni pẹlu awọn aṣayan Lagos lọpọlọpọ.',
        'market.platform.listproperty.desc': 'Portal ti o ni igbẹkẹle fun wiwa ile rẹ ti n bọ ni Lagos.',
        'market.platform.marketplace.desc': 'Awọn asopọ taara si awọn aṣoju ati awọn atokọ ti o jẹrisi.',
        'market.platform.tiktok.desc': 'Wo awọn irin-ajo ile gidi-akoko ati awọn iṣere aṣoju.',
        'market.tip.social': 'Imọran: Wa awọn iru ohun-ini wọnyi lori TikTok & Instagram',
        'market.tabs.platforms': 'Awọn iru ẹrọ',
        'market.tabs.agents': 'Awọn Aṣoju Ifọwọsi',
        'market.category.individual': 'Awọn aṣoju',
        'market.category.agencies': 'Awọn ile-iṣẹ',
        'market.category.offices': 'Awọn ọfiisi',
        'market.category.social': 'Soshiali',
        'market.verified': 'Aṣoju Ifọwọsi',
        'market.loading': 'Ngbe awọn aṣoju...',
        'market.call': 'Pe Ile-iṣẹ',
        'market.website': 'Oju opo wẹẹbu',
        'market.whatsapp': 'Iwiregbe WhatsApp',
        'market.premium.title': 'Gbe lọ si Ere',
        'market.premium.text': 'Ṣii awọn aṣoju, awọn ile-iṣẹ, ati awọn kapa TikTok ti a fọwọsi lati wa ile rẹ.',
        'market.premium.btn': 'Muu Wiwọle Pro ṣiṣẹ',
        'market.premium.success.title': 'Kaabọ si Ere!',
        'market.premium.success.text': 'O ni iraye si ni kikun si itọsọna aṣoju wa ati gbogbo awọn ẹya ere.',
        'market.premium.success.btn': 'Ṣawari Awọn Aṣoju Bayi',
        'property.type.self_contain': 'Iyẹwu Kan (Self Contained)',
        'property.type.single_room': 'Iyẹwu Kanṣoṣo',
        'property.type.flat_1': 'Iyẹwu Kan ati rọgbọkú',
        'property.type.flat_2': 'Iyẹwu Meji',
        'property.type.flat_3': 'Iyẹwu Mẹta',
        'property.type.duplex': 'Ile Alaja',
        'property.type.shared': 'Iyẹwu Ajọpin',
        'quiz.progress': 'Ibeere {0} ninu {1}',
        'quiz.multi_select': 'Aṣayan pupọ ṣiṣẹ',
        'quiz.budget_label': 'Tabi tẹ isuna ọdun rẹ (₦):',
        'quiz.budget_placeholder': 'bi apẹẹrẹ 1,500,000',
        'quiz.next': 'Itele',
        'quiz.back': 'Pada',
        'quiz.results': 'Wo Awọn Abajade',
        'result.based_on': 'Da lori awọn idahun rẹ',
        'result.perfect_match': 'A Wa Ibaramu Pipe Rẹ',
        'result.top_rec': 'IṢẸRỌ TOP',
        'result.specific_spots': 'Gbiyanju awọn aaye pataki wọnyi:',
        'result.rent': 'Iyalo',
        'result.noise': 'Ariwo',
        'result.lifestyle': 'Igbesi aye',
        'result.power': 'Iná',
        'result.street_talk': 'Oro Opopona',
        'result.trending': 'NPESO',
        'result.complaints': 'Awọn ẹdun',
        'result.compliments': 'Iyìn',
        'result.explore_btn': 'Ṣawari {0}',
        'result.find_apt': 'Wa Iyẹwu Kan',
        'result.neighbors': 'Awọn aladugbo ti o sunmọ julọ',
        'result.other_options': 'Awọn aṣayan nla miiran',
        'result.retake': 'Tun Idanwo Ṣe',
        'result.no_match_title': 'Ìṣirò Ìṣúná Lagos',
        'explore.title': 'Ṣawari Awọn Agbegbe Lagos',
        'explore.subtitle': 'Ṣawari awọn iṣiro alaye nipa gbogbo agbegbe.',
        'explore.search_placeholder': 'Ṣawari agbegbe kan (fun apẹẹrẹ Yaba, Lekki)...',
        'explore.sort.alpha_asc': 'Ibere (A-Z)',
        'explore.sort.alpha_desc': 'Ibere (Z-A)',
        'explore.sort.price_asc': 'Iye owo (Kere si Ga)',
        'explore.sort.price_desc': 'Iye owo (Ga si Kere)',
        'explore.avg_rent': 'Iyalo Apapọ',
        'explore.experience_title': 'Ni iriri Lagos',
        'explore.experience_subtitle': 'Awọn atokọ ti a ti ṣatunṣe ti ibiti o ti lọ ati ohun ti o yẹ ki o jẹ.',
        'explore.visit_title': 'Awọn aaye ti o nilo lati ṣabẹwo',
        'explore.eat_title': 'Kini lati jẹ',
        'explore.details.price_range': 'Iye Owo',
        'explore.details.vibe': 'Gbigbọn / Ariwo',
        'explore.details.commute': 'Aago Irin-ajo (Iwakọ)',
        'explore.details.to_vi': 'Si Victoria Island',
        'explore.details.to_ikeja': 'Si Ikeja (Central)',
        'explore.details.localities': 'Awọn agbegbe inu & Awọn aaye',
        'explore.details.hotspots': 'Awọn Hotspots Gbajumọ',
        'explore.details.proximity': 'Itoju si Awọn Agbegbe Miiran',
        'explore.details.distance_note': '*Awọn ijinna jẹ isunmọ.',
        'explore.details.ready_title': 'Ṣe o ti ṣetan lati lọ si {0}?',
        'explore.details.ready_text': 'Sopọ pẹlu awọn aṣoju ti o jẹrisi ki o ṣawari awọn iyẹwu ni {0} ni bayi.',
        'explore.details.find_btn': 'Wa Iyẹwu Kan',
        'explore.details.quiz_note': 'Ṣe eyi dabi rẹ? {0} lati rii daju!',
        'explore.details.take_quiz': 'Ṣe idanwo naa',
        'explore.details.street_talk': 'ORO OPOPONA',
        'explore.details.local_perks': 'AWON ANFAANI IBILE',
        'explore.details.mapping_note': "A ṣì ń ṣàpẹẹrẹ àwọn ibi tí ó dára jù lọ ní {0}. Ṣayẹwo sẹhin laipẹ fun ounjẹ ati awọn iṣeduro ere idaraya!",
        'about.title': 'Nipa LagosFit',
        'about.subtitle': 'A n ran ọ lọwọ lati wa aaye rẹ ninu rudurudu ati ẹwa ti Lagos.',
        'about.story_title': 'Itan Wa',
        'about.story_text': 'Lagos jẹ larinrin, iyara-iyara, ati nigba miiran o lagbara pupọ. Pẹlu diẹ sii ju awọn miliọnu 20 eniyan ati awọn dosinni ti awọn agbegbe alailẹgbẹ, wiwa aaye to tọ lati pe ile jẹ ipenija. LagosFit ni a bi jade ninu imọran ti o rọrun: Kini ti o ba le rii agbegbe pipe rẹ ni iṣẹju 30 nikan? A darapọ data lori iyalo, awọn akoko gbigbe, ati awọn gbigbọn igbesi aye lati baamu ọ pẹlu agbegbe Lagos rẹ ti o dara julọ.',
        'about.values_title': 'Kilode Ti A Fi N Ṣe Eyi',
        'about.value1_title': 'Ifi agbara mu',
        'about.value1_text': 'Fifun ọ ni alaye ti o nilo lati ṣe awọn ipinnu ile ọlọgbọn.',
        'about.value2_title': 'Otitọ',
        'about.value2_text': 'Data gidi nipa awọn agbegbe Lagos gidi. Ko si suga-bo.',
        'about.value3_title': 'Iṣẹ-ṣiṣe',
        'about.value3_text': 'Sode ile jẹ lile. Idanwo yii ko yẹ ki o jẹ.',
        'about.contact_title': 'Gba Ni Ifọwọkan',
        'about.contact_text': 'Ṣe o ni awọn didaba tabi o kan fẹ lati sọ hello? Gbe wa a ifiranṣẹ.',
        'about.contact_btn': 'Pe Wa',
        'footer.tagline': 'Ọna ọlọgbọn lati wa agbegbe pipe rẹ ni Lagos. Pẹlu data, otitọ, ati irọrun.',
        'footer.explore': 'Ṣawari',
        'footer.company': 'Ile-iṣẹ',
        'footer.connect': 'Sopọ',
        'footer.contact': 'Olubasọrọ',
        'footer.privacy': 'Ilana Aṣiri',
        'footer.built_for': 'Itumọ ti fun Lagos.',
        'review.title': 'Awọn atunwo Olumulo',
        'review.share_exp': 'Pin Iriri Rẹ',
        'review.pro_only': 'Awọn ọmọ ẹgbẹ Pro nikan le fi awọn atunwo silẹ. Ṣe igbesoke lati ṣe iranlọwọ fun agbegbe!',
        'review.upgrade_btn': 'Igbesoke si Pro',
        'review.your_rating': 'Rating rẹ',
        'review.your_comment': 'Ọrọ rẹ',
        'review.placeholder': 'Bawo ni o ṣe ri bi gbigbe nibi? Ṣe apejuwe gbigbọn, aabo, ati awọn ohun elo...',
        'review.submitted': 'Atunwo ti silẹ!',
        'review.post_btn': 'Fi Atunwo ranṣẹ',
        'review.submitting': 'Fifiranṣẹ...',
        'review.loading': 'Nkojọpọ awọn atunwo...',
        'review.no_reviews': 'Ko si awọn atunwo sibẹsibẹ. Jẹ akọkọ lati pin awọn ero rẹ!',
        'auth.login_title': 'Kaabo Pada',
        'auth.login_subtitle': 'Ṣetan lati wa agbegbe Lagos rẹ ti o tọ?',
        'auth.google_btn': 'Tẹsiwaju pẹlu Google',
        'auth.or_email': 'tabi wọle pẹlu imeeli',
        'auth.email_label': 'Adirẹsi imeeli',
        'auth.password_label': 'Ọrọigbaniwọle',
        'auth.name_label': 'Oruko ni kikun',
        'auth.login_btn': 'Wọle',
        'auth.register_title': 'Ṣẹda Akọọlẹ',
        'auth.register_subtitle': 'Darapọ mọ LagosFit lati ṣafipamọ itan wiwa rẹ ati diẹ sii.',
        'auth.register_btn': 'Ṣẹda Akọọlẹ',
        'auth.forgot_password': 'Gbagbe ọrọ igbaniwọle rẹ?',
        'auth.no_account': 'Ṣe o ko ni akọọlẹ kan?',
        'auth.register_link': 'Forukọsilẹ nibi',
        'auth.have_account': 'Ṣe o ti ni akọọlẹ tẹlẹ?',
        'auth.login_link': 'Wọle dipo',
        'auth.forgot_title': 'Tun Ọrọigbaniwọle to',
        'auth.forgot_subtitle': 'Tẹ imeeli rẹ sii a yoo fi ọna asopọ atunto ranṣẹ si ọ.',
        'auth.reset_btn': 'Firanṣẹ Ọna asopọ Atunto',
        'auth.back_to_login': 'Pada si Wọle',
        'auth.reset_success': 'Ona asopọ atunto ti firanṣẹ! Ṣayẹwo imeeli rẹ.',
        'auth.reset_check_email': 'Ṣayẹwo Imeeli Rẹ',
        'auth.reset_sent_to': 'A fi ọna asopọ atunto ọrọ igbaniwọle ranṣẹ si {0}.',
        'auth.reset_instruction': 'Tẹ ọna asopọ ninu imeeli lati tun ọrọ igbaniwọle rẹ to.',
        'auth.reset_not_received': "Ṣe o ko gba?",
        'auth.reset_spam_note': 'Ṣayẹwo folda spam rẹ tabi',
        'auth.reset_try_again': 'tun gbiyanju',
        'auth.error.user_not_found': 'Ko si akọọlẹ ti a rii pẹlu imeeli yii.',
        'auth.error.wrong_password': 'Ọrọigbaniwọle ti ko tọ. Tun gbiyanju.',
        'auth.error.invalid_credential': 'Imeeli tabi ọrọ igbaniwọle jẹ aṣiṣe.',
        'auth.error.too_many_requests': 'Awọn igbiyanju pupọ ju. Jọwọ duro diẹ.',
        'auth.error.popup_closed': 'Ferese agbejade ti wa ni pipade. Tun gbiyanju.',
        'auth.error.network_failed': 'Aṣiṣe nẹtiwọọki. Ṣayẹwo asopọ rẹ.',
        'auth.error.generic': 'Wíwọlé kuna. Jọwọ tun gbiyanju.',
        'auth.error.email_in_use': 'Akọọlẹ kan pẹlu imeeli yii wa tẹlẹ.',
        'auth.error.weak_password': 'Ọrọigbaniwọle gbọdọ jẹ o kere ju awọn ohun kikọ 6.',
        'auth.error.invalid_email': 'Jọwọ tẹ adirẹsi imeeli to wulo sii.',
        'auth.error.passwords_dont_match': 'Awọn ọrọ igbaniwọle ko baamu.',
        'pricing.title': 'Iye owo ti o rọrun ati kedere',
        'pricing.subtitle': 'Darapọ mọ awọn olumulo 5,000+ ti n wa ile pipe wọn.',
        'pricing.badge': 'MÚ ÌWÁ RẸ SÍWÁJÚ',
        'pricing.monthly': 'Oshooṣu',
        'pricing.yearly': 'Ọdọọdun',
        'pricing.free_name': 'Olùwakiri',
        'pricing.free_desc': 'Fun awọn ti n wo ni ẹẹkan.',
        'pricing.free_price': '₦0',
        'pricing.forever': '/ titi ayeraye',
        'pricing.pro_name': 'LagosFit Pro',
        'pricing.pro_desc': 'Fun awọn oluwadi ile pataki.',
        'pricing.popular': 'GBAJUMỌ',
        'pricing.per_period': '/ {0}',
        'pricing.current_plan': 'Eto lọwọlọwọ',
        'pricing.get_started': 'Bẹrẹ',
        'pricing.already_pro': 'O ti jẹ Pro tẹlẹ',
        'pricing.upgrade_btn': 'Dí Pro',
        'pricing.secure_payment': 'Isanwo to ni aabo',
        'pricing.via_paystack': 'Nipasẹ Paystack',
        'pricing.instant_activation': 'Ibere kiakia',
        'pricing.unlock_pro': 'Šii awọn ẹya pro bayi',
        'pricing.feat1': 'Wọle si awọn iru ẹrọ ohun-ini',
        'pricing.feat2': 'Awọn aṣoju to daju pẹlu awọn olubasọrọ',
        'pricing.feat3': 'Awọn ile-iṣẹ pẹlu awọn oju opo wẹẹbu ati imeeli',
        'pricing.feat4': 'Awọn ipo ọfiisi kọja Lagos',
        'pricing.feat5': 'Awọn ọna asopọ TikTok fun awọn irin-ajo ile',
        'pricing.feat6': 'Awọn ọna asopọ iwiregbe WhatsApp',
        'profile.title': 'Oju-iwe rẹ',
        'profile.edit_btn': 'Ṣatunkọ Oju-iwe',
        'profile.save_btn': 'Fipamọ',
        'profile.saving': 'Nfipamọ...',
        'profile.cancel': 'Fagilee',
        'profile.name_label': 'Orukọ rẹ',
        'profile.name_placeholder': 'Oruko ni kikun',
        'profile.set_name': 'Sọ orukọ rẹ',
        'profile.updated_success': 'Oju-iwe rẹ ti ni imudojuiwọn!',
        'profile.updated_fail': 'Imudojuiwọn kuna.',
        'profile.avatar_updated': 'Aworan rẹ ti ni imudojuiwọn!',
        'profile.avatar_optimizing': 'Nmu aworan dara si...',
        'profile.avatar_saving': 'Nfipamọ aworan...',
        'profile.shortlist_title': 'Awọn agbegbe rẹ',
        'profile.no_favorites': 'O ko tii fipamọ agbegbe eyikeyi.',
        'profile.explore_btn': 'Ṣawari Awọn agbegbe',
        'profile.preferences': 'Awọn eto',
        'profile.alerts': 'Awọn titaniji idiyele',
        'profile.summary': 'Akopọ Ọja Ọsẹ',
        'profile.recent_quiz': 'Idanwo aipẹ',
        'profile.view_all': 'Wo Gbogbo rẹ̀',
        'profile.no_history': 'Ko si itan idanwo.',
        'profile.take_quiz': 'Ṣe Idanwo',
        'profile.latest_rec': 'Agbegbe ti a ṣeduro kẹhin',
        'profile.review_result': 'Wo abajade ni kikun',
        'profile.pro_badge': 'PRO',
        'profile.upgrade_title': 'Dí Pro',
        'profile.upgrade_desc': 'Gba awọn ijabọ, awọn iṣiro aabo, ati awọn olubasọrọ aṣoju.',
        'profile.view_pricing': 'Wo Iye owo',
        'history.title': 'Itan Wiwa Rẹ',
        'history.subtitle': 'Ṣatunyẹwo awọn abajade idanwo rẹ tẹlẹ.',
        'history.no_history': 'Ko si itan. Ṣe idanwo naa lati bẹrẹ!',
        'history.back_to_profile': 'Pada si Oju-iwe rẹ',
        'buddy.welcome': "Kaabo! Buddy ni orukọ mi, oluranlọwọ LagosFit rẹ. Mo mọ Lagos bi owo mi. Beere ohunkohun nipa idiyele ile ni Lekki, awọn ibi isere ni Ikeja, tabi bi o ṣe le rii awọn aṣoju to daju!"
    },
    ig: {
        'landing.title': 'Kedu akụkụ Lagos dabara gị?',
        'landing.subtitle': 'Chọta akụkụ Lagos nke kwekọrọ n’ụdị ndụ gị, ego gị, na ọchịchọ gị.',
        'landing.cta': 'Chọta Ihe Dabara Gị',
        'landing.time': 'Ọ na-ewe sekọnd 30 • Site na data ziri ezi',
        'landing.how.title': 'Otu o si arụ ọrụ',
        'landing.how.subtitle': 'Chọta ihe dabara gị n’ime usoro 3 dị mfe',
        'landing.how.step1.title': 'Zaa ajụjụ',
        'landing.how.step1.text': 'Gwa anyị gbasara ego gị, ebe ọrụ gị, na ndụ gị.',
        'landing.how.step2.title': 'Chọta Ihe Dabara Gị',
        'landing.how.step2.text': 'Algoridimu anyị na-achọtara gị mpaghara kacha mma ozugbo.',
        'landing.how.step3.title': 'Chọpụta',
        'landing.how.step3.text': 'Hụ nkọwa gbasara ụlọ ọhụrụ gị.',
        'landing.trending.title': 'Mpaghara ndị ama ama',
        'landing.trending.subtitle': 'Ebe ndị kacha mma mmadụ niile na-ekwu maka ya n’izu a.',
        'landing.trending.label': 'Na-ewu ewu',
        'landing.trending.starts': 'Malite na',
        'landing.view_history': 'Hụ Akụkọ',
        'nav.home': 'Ụlọ',
        'nav.how': 'Otu o si arụ ọrụ',
        'nav.explore': 'Chọpụta mpaghara',
        'nav.market': 'Ahịa',
        'nav.about': 'Maka Anyị',
        'nav.pricing': 'Ọrụ Ego',
        'nav.profile': 'Aha m',
        'nav.admin': 'Ogwe nchịkwa',
        'nav.history': 'Akụkọ m',
        'nav.signout': 'Pụọ',
        'nav.signin': 'Banye',
        'nav.all_areas': 'Mpaghara Niile',
        'nav.find_match': 'Chọta Ihe Dabara Gị',
        'market.title.main': 'Ebe Ịnọrọ',
        'market.subtitle.main': 'Ị hụla mpaghara gị? Ugbu a ka anyị chọta ụlọ gị. Chọọ ikpo okwu nkenke, kpakọrịta ndị ọrụ, ma chọgharịa ndepụta enyochara.',
        'market.select_area': 'Họrọ Mpaghara',
        'market.search_placeholder': 'Chọọ mpaghara...',
        'market.searching_in': 'Na-achọ ugbu a na',
        'market.search_btn': 'Chọọ',
        'market.safety.title': 'Ndụmọdụ Ndị Ọrụ & Nchebe',
        'market.safety.subtitle': 'Otu esi agagharị n’ahịa mgbazinye Lagos n’enweghị nsogbu.',
        'market.safety.tip1.title': 'Nyochaa tupu ị kwụọ ụgwọ',
        'market.safety.tip1.text': 'Akpanyela ego maka ụlọ ị na-ahụghị anya. Ndị ohi juru n’ịntanetị.',
        'market.safety.tip2.title': 'Jụọ maka onye nwe ụlọ',
        'market.safety.tip2.text': 'Gbaa mbọ hụ na onye ọrụ ahụ nwere ikike. Rịọ ka ị hụ onye na-elekọta ụlọ ma ọ bụ onye nwe ụlọ mgbe ịmechara.',
        'market.safety.tip3.title': 'Lelee ikpo okwu dị iche iche',
        'market.safety.tip3.text': 'Enwere ike depụta otu ụlọ ahụ n’ọtụtụ ikpo okwu nwere ọnụ ahịa dị iche iche. Na-atụnyere ha mgbe niile.',
        'market.directory.title': 'Akwụkwọ Ndị Ọrụ & Ụlọ Ọrụ',
        'market.directory.subtitle': 'Ndị ọrụ ụlọ enyochara, ụlọ ọrụ ndị a tụrụ raba, na aka mgbasa ozi ọha — ihe niile n’otu ebe.',
        'market.platform.propertypro.desc': 'Otu n’ime ikpo okwu nchọta ụlọ kacha ibu n’Africa.',
        'market.platform.naijahouses.desc': 'Ndepụta Lagos zuru oke yana akụrụngwa enyochara.',
        'market.platform.myplace.desc': 'Nchọta ihe onwunwe ọgbara ọhụrụ nwere nhọrọ Lagos dị iche iche.',
        'market.platform.listproperty.desc': 'Portal tụkwasịrị obi maka ịchọta ụlọ Lagos gị ọzọ.',
        'market.platform.marketplace.desc': 'Njikọ ozugbo na ndị ọrụ na ndepụta enyochara.',
        'market.platform.tiktok.desc': 'Lelee njem ụlọ ozugbo yana nkọwa ndị ọrụ.',
        'market.tip.social': 'ICE: Chọọ ụdị ụlọ ndị a na TikTok & Instagram',
        'market.tabs.platforms': 'Ikpo okwu',
        'market.tabs.agents': 'Ndị ọrụ enyochara',
        'market.category.individual': 'Ndị ọrụ',
        'market.category.agencies': 'Ụlọ ọrụ',
        'market.category.offices': 'Ọfịs',
        'market.category.social': 'Social',
        'market.verified': 'Onye Ọrụ Enyochara',
        'market.loading': 'Na-ebunye ndị ọrụ...',
        'market.call': 'Kpọọ Ụlọ Ọrụ',
        'market.website': 'Ebe nrụọrụ weebụ',
        'market.whatsapp': 'WhatsApp Chat',
        'market.premium.title': 'Gbagoo na Premium',
        'market.premium.text': 'Chọpụta ndị ọrụ, ụlọ ọrụ, na aka TikTok enyochara iji chọta ụlọ gị.',
        'market.premium.btn': 'Mee ka Pro Access rụọ ọrụ',
        'market.premium.success.title': 'Nabata na Premium!',
        'market.premium.success.text': 'Ugbu a ị nwere ohere zuru oke na akwụkwọ ndị ọrụ anyị na atụmatụ ndị ọzọ.',
        'market.premium.success.btn': 'Chọpụta ndị ọrụ ugbu a',
        'property.type.self_contain': 'Ụlọ Self-contain',
        'property.type.single_room': 'Ụlọ Nanị ya',
        'property.type.flat_1': 'Ụlọ Ime Anyị Otu',
        'property.type.flat_2': 'Ụlọ Ime Anyị Abụọ',
        'property.type.flat_3': 'Ụlọ Ime Anyị Atọ',
        'property.type.duplex': 'Ụlọ Alaja',
        'property.type.shared': 'Ụlọ Ajọkọ riri',
        'quiz.progress': 'Ajụjụ {0} n’ime {1}',
        'quiz.multi_select': 'Nhọrọ dị iche iche agbakwunyere',
        'quiz.budget_label': 'Ma ọ bụ pịnye ego ole ị nwere n’afọ (₦):',
        'quiz.budget_placeholder': 'dịka 1,500,000',
        'quiz.next': 'Ihe na-esote',
        'quiz.back': 'Laa azụ',
        'quiz.results': 'Hụ nsonaazụ',
        'result.based_on': 'Dabere na azịza gị',
        'result.perfect_match': 'Anyị achọtala onye kacha gị mma',
        'result.top_rec': 'NDỤMỌDỤ kacha',
        'result.specific_spots': 'Gbalịa ebe ndị a kapịrị ọnụ:',
        'result.rent': 'Rent',
        'result.noise': 'Ụda',
        'result.lifestyle': 'Obi ndụ',
        'result.power': 'Ike',
        'result.street_talk': 'Okwu okporo ụzọ',
        'result.trending': 'IHE NA-EME',
        'result.complaints': 'Mkpesa',
        'result.compliments': 'Ihe otuto',
        'result.explore_btn': 'Chọgharịa {0}',
        'result.find_apt': 'Chọta ụlọ',
        'result.neighbors': 'Ndị agbata obi kacha nso',
        'result.other_options': 'Nhọrọ ndị ọzọ dị mma',
        'result.retake': 'Mee ajụjụ ọzọ',
        'result.no_match_title': 'Ezigbo lelee ego gị',
        'explore.title': 'Chọpụta mpaghara Lagos',
        'explore.subtitle': 'Chọpụta nkọwa miri emi gbasara agbata obi ọ bụla.',
        'explore.search_placeholder': 'Chọọ mpaghara (dịka Yaba, Lekki)...',
        'explore.sort.alpha_asc': 'Alphabetical (A-Z)',
        'explore.sort.alpha_desc': 'Alphabetical (Z-A)',
        'explore.sort.price_asc': 'Ego (Obere gaa na Elu)',
        'explore.sort.price_desc': 'Ego (Elu gaa na Obere)',
        'explore.avg_rent': 'Ego Rent Apapọ',
        'explore.experience_title': 'Nweta Lagos',
        'explore.experience_subtitle': 'Ndepụta ebe ị ga-aga na ihe ị ga-eri.',
        'explore.visit_title': 'Ebe ndị ị kwesịrị ileta',
        'explore.eat_title': 'Ihe ị ga-eri',
        'explore.details.price_range': 'Ọnụ ego',
        'explore.details.vibe': 'Vibe / Noise',
        'explore.details.commute': 'Oge njem (Ikwọ ụgbọelu)',
        'explore.details.to_vi': 'Gaa Victoria Island',
        'explore.details.to_ikeja': 'Gaa Ikeja (Central)',
        'explore.details.localities': 'Mpaghara ndị dị n’ime',
        'explore.details.hotspots': 'Ebe ndị ama ama',
        'explore.details.proximity': 'Ịdị nso na mpaghara ndị ọzọ',
        'explore.details.distance_note': '*Ebe ndị a bụ nleba anya.',
        'explore.details.ready_title': 'Ị dịla njikere ịkwaga na {0}?',
        'explore.details.ready_text': 'Kpọtụrụ ndị ọrụ enyochara ma chọọ ụlọ na {0} ugbu a.',
        'explore.details.find_btn': 'Chọta ụlọ',
        'explore.details.quiz_note': 'Ihe a ọ dị ka gị? {0} ka ị mata nke ọma!',
        'explore.details.take_quiz': 'Mee ajụjụ ahụ',
        'explore.details.street_talk': 'OKWU OKPORO ỤZỌ',
        'explore.details.local_perks': 'PERKS NKE IBILE',
        'explore.details.mapping_note': "Anyị ka na-achọta ebe kacha mma na {0}. Laghachi azụ n’oge na-adịghị anya maka nri na egwuregwu!",
        'about.title': 'Maka LagosFit',
        'about.subtitle': 'Na-enyere gị aka ịchọta ebe gị na ọgba aghara na mma Lagos.',
        'about.story_title': 'Akụkọ Anyị',
        'about.story_text': 'Lagos na-ekwo ekwo ma na-aga ngwa ngwa. N’inwe ihe karịrị nde mmadụ iri abụọ na ọtụtụ mpaghara dị iche iche, ịchọta ebe kwesịrị ekwesị a ga-akpọ gị ka ụlọ bụ nnukwu ihe ịma aka. LagosFit si n’echiche dị mfe pụta: Gịnị ma ọ bụrụ na ị ga-ahụ mpaghara gị zuru oke n’ime naanị sekọnd 30? Anyị na-ejikọta data gbasara mgbazinye, oge njem, na ụdị ndụ iji kwekọọ gị na mpaghara Lagos gị kacha mma.',
        'about.values_title': 'Ihe Mere Anyị Na-eji Eme Nke A',
        'about.value1_title': 'Inye Ike',
        'about.value1_text': 'Inye gị ozi ị chọrọ iji mee mkpebi ụlọ mara mma.',
        'about.value2_title': 'Ezigbo',
        'about.value2_text': 'Ezigbo data gbasara mpaghara Lagos. Ọ dịghị ihe a na-ekpuchi.',
        'about.value3_title': 'Mfe',
        'about.value3_text': 'Ịchọ ụlọ na-esiri ike. Ajụjụ a ekwesịghị ịdị otú ahụ.',
        'about.contact_title': 'Kpọtụrụ Anyị',
        'about.contact_text': 'Ị nwere aro ma ọ bụ na ị chọrọ naanị ikwu ndewo? zitere anyị ozi.',
        'about.contact_btn': 'Kpọtụrụ Anyị',
        'footer.tagline': 'Ụzọ amamihe dị na ya isi chọta agbata obi gị kacha mma na Lagos. Site na data, eziokwu, na mfe.',
        'footer.explore': 'Chọpụta',
        'footer.company': 'Ụlọ ọrụ',
        'footer.connect': 'Jikọọ',
        'footer.contact': 'Onye kpakpando',
        'footer.privacy': 'Amụma Nzuzo',
        'footer.built_for': 'Emere maka Lagos.',
        'review.title': 'Nlebanya ndị ọrụ',
        'review.share_exp': 'Kesaa amamihe gị',
        'review.pro_only': 'Naanị ndị otu Pro nwere ike ide nlebanya. Melite ka ị nyere anyị aka!',
        'review.upgrade_btn': 'Melite na Pro',
        'review.your_rating': 'Rating gị',
        'review.your_comment': 'Okwu gị',
        'review.placeholder': 'Kedu ka ibi ebe a siri dị? Kọwaa vibe, nchekwa, na ihe ndị ọzọ...',
        'review.submitted': 'Edeela nlebanya!',
        'review.post_btn': 'Mee nlebanya',
        'review.submitting': 'Na-eziga...',
        'review.loading': 'Na-ebubata nlebanya...',
        'review.no_reviews': 'Ọ nweghị nlebanya ugbu a. Buru ụzọ kọọ ihe ị chere!',
        'auth.login_title': 'Nnọọ ọzọ',
        'auth.login_subtitle': 'Ị dịla njikere ịchọta mpaghara Lagos gị kacha mma?',
        'auth.google_btn': 'Gaa n’ihu na Google',
        'auth.or_email': 'ma ọ bụ jiri email banye',
        'auth.email_label': 'Adreesị ozi-e',
        'auth.password_label': 'Paswọdu',
        'auth.name_label': 'Aha gị n’uju',
        'auth.login_btn': 'Banye',
        'auth.register_title': 'Mepụta Akaụntụ',
        'auth.register_subtitle': 'Soro LagosFit chọta mpaghara Lagos gị mara mma.',
        'auth.register_btn': 'Mepụta Akaụntụ',
        'auth.forgot_password': 'Ị chefuru paswọdu gị?',
        'auth.no_account': 'Ị nweghị akaụntụ?',
        'auth.register_link': 'Debanye aha ebe a',
        'auth.have_account': 'Ị nwere akaụntụ ugbua?',
        'auth.login_link': 'Banye ebe ọzọ',
        'auth.forgot_title': 'Tọgharịa Paswọdu',
        'auth.forgot_subtitle': 'Tinye email gị ka anyị zitere gị link maka tọgharịa ya.',
        'auth.reset_btn': 'Zipu Link Tọgharịa',
        'auth.back_to_login': 'Laghachi na Login',
        'auth.reset_success': 'Ezipụla link tọgharịa! Lelee email gị.',
        'auth.reset_check_email': 'Lelee Email Gị',
        'auth.reset_sent_to': 'Anyị zitere link maka tọgharịa paswọdu gị na {0}.',
        'auth.reset_instruction': 'Pịa link dị n’ime ozi-e ahụ iji tọgharịa paswọdu gị.',
        'auth.reset_not_received': "Ị nwetaghị ya?",
        'auth.reset_spam_note': 'Lelee fọlda spam gị ma ọ bụ',
        'auth.reset_try_again': 'nwaa ọzọ',
        'auth.error.user_not_found': 'Anyị ahụghị akaụntụ nwere email a.',
        'auth.error.wrong_password': 'Paswọdu adịghị mma. Nwaa ọzọ.',
        'auth.error.invalid_credential': 'Email ma ọ bụ paswọdu adịghị mma.',
        'auth.error.too_many_requests': 'Inwala nke ukwuu. Chere ntakịrị.',
        'auth.error.popup_closed': 'Emechiri windo mmapụta ahụ. Nwaa ọzọ.',
        'auth.error.network_failed': 'Nsogbu netwọk. Lelee data gị.',
        'auth.error.generic': 'Ntinye akaụntụ ahụ agaghị. Biko nwaa ọzọ.',
        'auth.error.email_in_use': 'Akaụntụ nwere email a ugbua.',
        'auth.error.weak_password': 'Paswọdu ga-abụ opekata mpe mkpụrụedemede isii.',
        'auth.error.invalid_email': 'Biko tinye adreesị email dị mma.',
        'auth.error.passwords_dont_match': 'Paswọdu adịghị mma.',
        'pricing.title': 'Ọnụ ahịa dị mfe ma doo anya',
        'pricing.subtitle': 'Soro ndị ọrụ 5,000+ na-achọta ụlọ ha kacha mma.',
        'pricing.badge': 'KWALITE ỌCHỊCHỊ GỊ',
        'pricing.monthly': 'Kwa ọnwa',
        'pricing.yearly': 'Kwa afọ',
        'pricing.free_name': 'Onye nyocha',
        'pricing.free_desc': 'Maka ndị na-ekiri ekiri.',
        'pricing.free_price': '₦0',
        'pricing.forever': '/ rue mgbe ebighị ebi',
        'pricing.pro_name': 'LagosFit Pro',
        'pricing.pro_desc': 'Maka ndị na-achọ ụlọ n’ezie.',
        'pricing.popular': 'GBAJUMỌ',
        'pricing.per_period': '/ {0}',
        'pricing.current_plan': 'Atụmatụ gị',
        'pricing.get_started': 'Bido ugbu a',
        'pricing.already_pro': 'Ị bụbu Pro',
        'pricing.upgrade_btn': 'Banye Pro',
        'pricing.secure_payment': 'Ịkwụ ụgwọ echekwara',
        'pricing.via_paystack': 'Site na Paystack',
        'pricing.instant_activation': 'Mmalite ozugbo',
        'pricing.unlock_pro': 'Mepee atụmatụ pro ugbu a',
        'pricing.feat1': 'Nweta igbe ọrụ akụrụngwa',
        'pricing.feat2': 'Ndị ọrụ doro anya na nọmba ha',
        'pricing.feat3': 'Ụlọ ọrụ nwere webụsaịtị na email',
        'pricing.feat4': 'Ụlọ ọrụ ha n’ime Lagos',
        'pricing.feat5': 'Njikọ TikTok maka nlegharị ụlọ',
        'pricing.feat6': 'Njikọ WhatsApp',
        'profile.title': 'Ihu gị',
        'profile.edit_btn': 'Gbanwee ihu gị',
        'profile.save_btn': 'Chekwaa',
        'profile.saving': 'Na-echekwa...',
        'profile.cancel': 'Kagbuo',
        'profile.name_label': 'Aha gị',
        'profile.name_placeholder': 'Aha gị n’uju',
        'profile.set_name': 'Tinye aha gị',
        'profile.updated_success': 'Emezigharịrị ihu gị nke ọma!',
        'profile.updated_fail': 'Ihe gbanwere emeghị.',
        'profile.avatar_updated': 'Emezigharịrị foto gị!',
        'profile.avatar_optimizing': 'Na-emezigharị foto...',
        'profile.avatar_saving': 'Na-echekwa foto...',
        'profile.shortlist_title': 'Mpaghara ị họọrọ',
        'profile.no_favorites': 'Ị debeghị mpaghara ọ bụla.',
        'profile.explore_btn': 'Nyochaa Mpaghara',
        'profile.preferences': 'Ntọala',
        'profile.alerts': 'Ozi maka ọnụ ahịa',
        'profile.summary': 'Akụkọ Azụmahịa Kwa Izu',
        'profile.recent_quiz': 'Idanwo aipẹ',
        'profile.view_all': 'Hụ Ha Niile',
        'profile.no_history': 'Ọ nweghị itan idanwo.',
        'profile.take_quiz': 'Mee Idanwo',
        'profile.latest_rec': 'Mpaghara kachasị mma e gosiri gị',
        'profile.review_result': 'Hụ abajade niile',
        'profile.pro_badge': 'PRO',
        'profile.upgrade_title': 'Banye Pro',
        'profile.upgrade_desc': 'Gba akụkọ, stats nchekwa, na nọmba ndị ọrụ.',
        'profile.view_pricing': 'Hụ Ọnụ Ahịa',
        'history.title': 'Itan Ọchịchị Gị',
        'history.subtitle': 'Laghachiri lelee abajade idanwo gị mbụ.',
        'history.no_history': 'Ọ nweghị itan. Mee idanwo ahụ iji bido!',
        'history.back_to_profile': 'Laghachi na ihu gị',
        'buddy.welcome': "Nnọọ! Abụ m Buddy, onye enyemaka LagosFit gị. Amara m Lagos nke ọma. Jụọ m ihe ọ bụla gbasara ọnụ ụlọ na Lekki, ebe dị mma na Ikeja, ma ọ bụ otu ị ga-esi nweta ndị ọrụ enyochara!"
    },
    ha: {
        'landing.title': 'Wane yankin Legas ne ya dace da ku?',
        'landing.subtitle': "Nemo yankin Legas da ya dace da salon rayuwar ku, kasafin ku, da abubuwan sha'awar ku.",
        'landing.cta': 'Nemo Abin da Ya Dace Da Kai',
        'landing.time': 'Zai ɗauki sakan 30 • Bisa ingantaccen bayanai',
        'landing.how.title': 'Yadda Yake Aiki',
        'landing.how.subtitle': 'Nemo abin da ya dace da kai a matakai 3 masu sauƙi',
        'landing.how.step1.title': 'Amsa Tambayoyi',
        'landing.how.step1.text': 'Faɗa mana game da kasafin kuɗin ku, wurin aiki, da salon rayuwar ku.',
        'landing.how.step2.title': 'Nemo Daidaituwa',
        'landing.how.step2.text': 'Algoridimu namu zai nemo muku mafi kyawun yankuna nan take.',
        'landing.how.step3.title': 'Bincika',
        'landing.how.step3.text': 'Duba cikakkun bayanai game da sabon gidan ku.',
        'landing.trending.title': 'Yankuna Masu Hada-hada',
        'landing.trending.subtitle': 'Manyan wuraren da kowa ke magana akai a wannan makon.',
        'landing.trending.label': 'Masu tasowa',
        'landing.trending.starts': 'Farawa daga',
        'landing.view_history': 'Duba Tarihi',
        'nav.home': 'Gida',
        'nav.how': 'Yadda Yake Aiki',
        'nav.explore': 'Bincika Yankuna',
        'nav.market': 'Kasuwa',
        'nav.about': 'Game Da Mu',
        'nav.pricing': 'Farashi',
        'nav.profile': 'Bayanina',
        'nav.admin': 'Gidan Gudanarwa',
        'nav.history': 'Tarihina',
        'nav.signout': 'Fita',
        'nav.signin': 'Shiga',
        'nav.all_areas': 'Dukkan Yankuna',
        'nav.find_match': 'Nemo Yankinka',
        'market.title.main': 'Cibiyar Masauki',
        'market.subtitle.main': 'Kun sami yankin ku? Yanzu bari mu nemo muku gida. Bincika dandamali, tuntuɓi wakilai, kuma duba bayanan da aka tabbatar.',
        'market.select_area': 'Zaɓi Yanki',
        'market.search_placeholder': 'Nemo yankuna...',
        'market.searching_in': 'Ana Bincike A Halin Yanzu A',
        'market.search_btn': 'Bincika',
        'market.safety.title': 'Shawarwari Wakilai & Tsaro',
        'market.safety.subtitle': 'Yadda zaka bi kasuwar haya ta Legas cikin aminci.',
        'market.safety.tip1.title': 'Tabbatar Kafin Biya',
        'market.safety.tip1.text': 'Kada ka taba biyan kudin gidan da ba ka gani da idonka ba. Masu damfara sun yi yawa a yanar gizo.',
        'market.safety.tip2.title': 'Tambayi Mai Gida',
        'market.safety.tip2.text': 'Tabbatar cewa wakilin yana da izini. Nemi ganin mai kula ko mai gida lokacin da aka gama komai.',
        'market.safety.tip3.title': 'Duba Dandamali Daban-daban',
        'market.safety.tip3.text': 'Ana iya sanya gida guda akan dandamali da yawa tare da farashi daban-daban. Koyaushe kwatanta su.',
        'market.directory.title': 'Kundin Wakilai & Hukumomi',
        'market.directory.subtitle': 'Ingantattun wakilai, hukumomin da aka kimanta, wuraren ofis, da shafukan sada zumunta — duka a wuri guda.',
        'market.platform.propertypro.desc': 'Daya daga cikin manyan dandali na neman kadarori a Afirka.',
        'market.platform.naijahouses.desc': 'Cikakkun jerin kadarorin Legas tare da ingantattun kadarori.',
        'market.platform.myplace.desc': 'Neman kadarori na zamani tare da zabuka daban-daban na Legas.',
        'market.platform.listproperty.desc': 'Wurin da za a iya amincewa da shi don nemo gidan ku na gaba a Legas.',
        'market.platform.marketplace.desc': 'Haɗin kai kai tsaye tare da ingantattun wakilai da jeri.',
        'market.platform.tiktok.desc': 'Kalli yawon shakatawa na gida na lokaci-lokaci da bayanan wakilai.',
        'market.tip.social': "SHAWARA: Nemo wadannan nau'ikan kadarorin a TikTok & Instagram",
        'market.tabs.platforms': 'Dandalin',
        'market.tabs.agents': 'Wakilai Karɓaɓɓu',
        'market.category.individual': 'Wakilai',
        'market.category.agencies': 'Hukumomi',
        'market.category.offices': 'Ofisoshi',
        'market.category.social': 'Soshiyal',
        'market.verified': 'Karɓaɓɓen Wakili',
        'market.loading': 'Ana loda wakilai...',
        'market.call': 'Kira Hukumar',
        'market.website': 'Yanar Gizo',
        'market.whatsapp': 'Tattaunawar WhatsApp',
        'market.premium.title': 'Haɓaka zuwa Premium',
        'market.premium.text': 'Bincika wakilai, hukumomi, da shafukan TikTok da aka tabbatar don nemo gidan ku.',
        'market.premium.btn': 'Kunna Pro Access',
        'market.premium.success.title': 'Sannu da zuwa Premium!',
        'market.premium.success.text': 'Yanzu kuna da cikakken damar shiga kundin wakilan mu da dukkan wasu ayyuka na musamman.',
        'market.premium.success.btn': 'Bincika wakilai yanzu',
        'property.type.self_contain': 'Gidan Self-contain',
        'property.type.single_room': 'Ɗaki Guda',
        'property.type.flat_1': 'Gida Mai Ɗaki 1',
        'property.type.flat_2': 'Gida Mai Ɗaki 2',
        'property.type.flat_3': 'Gida Mai Ɗaki 3',
        'property.type.duplex': 'Gidan Bene',
        'property.type.shared': 'Gidan Tarayya',
        'quiz.progress': 'Tambaya {0} cikin {1}',
        'quiz.multi_select': 'Zaba fiye da daya yana aiki',
        'quiz.budget_label': 'Ko rubuta kasafin kudin ku na shekara (₦):',
        'quiz.budget_placeholder': 'misali 1,500,000',
        'quiz.next': 'Gaba',
        'quiz.back': 'Baya',
        'quiz.results': 'Duba Sakamako',
        'result.based_on': 'Dangane da amsoshinku',
        'result.perfect_match': 'Mun Nemo Muku Daidai',
        'result.top_rec': 'SHAWARA TA FARKO',
        'result.specific_spots': 'Gwada wadannan takamaiman wurare:',
        'result.rent': 'Haya',
        'result.noise': 'Surutu',
        'result.lifestyle': 'Yanayin Rayuwa',
        'result.power': 'Wutar Lantarki',
        'result.street_talk': 'Zancen Kan Titin',
        'result.trending': 'MAI TASHE',
        'result.complaints': 'Korafe-korafe',
        'result.compliments': 'Yabo',
        'result.explore_btn': 'Bincika {0}',
        'result.find_apt': 'Nemo Gida',
        'result.neighbors': 'Maƙwabta Mafi Kusa',
        'result.other_options': 'Wasu manyan zaɓuka',
        'result.retake': 'Sake Yin Tambayoyi',
        'result.no_match_title': 'Gaskiyar Kasafin Kudin Legas',
        'explore.title': 'Bincika Yankunan Legas',
        'explore.subtitle': 'Bincika cikakkun bayanai game da kowane yanki.',
        'explore.search_placeholder': 'Nemo yanki (misali Yaba, Lekki)...',
        'explore.sort.alpha_asc': 'Tsarin Haruffa (A-Z)',
        'explore.sort.alpha_desc': 'Tsarin Haruffa (Z-A)',
        'explore.sort.price_asc': 'Farashi (Kasa zuwa Sama)',
        'explore.sort.price_desc': 'Farashi (Sama zuwa Kasa)',
        'explore.avg_rent': 'Kudin Hayar Matsakaici',
        'explore.experience_title': 'Fuskanci Legas',
        'explore.experience_subtitle': 'Jerin wuraren da za a je da abin da za a ci.',
        'explore.visit_title': 'Wuraren da ya kamata ku ziyarta',
        'explore.eat_title': 'Abin da za a ci',
        'explore.details.price_range': 'Yanayin Farashi',
        'explore.details.vibe': 'Yanayi / Surutu',
        'explore.details.commute': 'Lokacin Tafiya (Tuƙi)',
        'explore.details.to_vi': 'Zuwa Victoria Island',
        'explore.details.to_ikeja': 'Zuwa Ikeja (Babban Birni)',
        'explore.details.localities': 'Yankuna na Ciki',
        'explore.details.hotspots': 'Shahararrun Wurare',
        'explore.details.proximity': 'Kusancin sa da wasu Yankuna',
        'explore.details.distance_note': '*Nisan nan na kusan ne.',
        'explore.details.ready_title': 'Kun shirya yin kaura zuwa {0}?',
        'explore.details.ready_text': 'Tuntuɓi wakilai da aka tabbatar kuma bincika gidajen da ke akwai a {0} yanzu.',
        'explore.details.find_btn': 'Nemo Gida',
        'explore.details.quiz_note': 'Shin wannan yana kama da ku? {0} don tabbatarwa!',
        'explore.details.take_quiz': 'Yi tambayoyin',
        'explore.details.street_talk': 'ZANCEN KAN TITIN',
        'explore.details.local_perks': 'ABUBUWAN IBILE',
        'explore.details.mapping_note': "Har yanzu muna neman mafi kyawun wurare a {0}. Dawo nan gaba don shawarwarin abinci da wasanni!",
        'about.title': 'Game Da LagosFit',
        'about.subtitle': 'Taimaka muku nemo wurin ku a cikin rudani da kyan Legas.',
        'about.story_title': 'Labarin Mu',
        'about.story_text': 'Legas tana da kuzari, saurin gaske, kuma wani lokacin tana da wuyar gaske. Tare da sama da mutane miliyan 20 da ɗimbin unguwanni na musamman, nemo wurin da ya dace da za a kira gida ƙalubale ne. An haifi LagosFit ne sakamakon wani ra\'ayi mai sauƙi: Menene zai faru idan za ku iya samun cikakkiyar unguwarku a cikin sakan 30 kawai? Muna haɗa bayanai kan haya, lokutan zirga-zirga, da yanayin rayuwa don daidaita ku da ingantaccen yankin Legas.',
        'about.values_title': 'Me Yasa Muke Yin Wannan',
        'about.value1_title': 'Ƙarfafawa',
        'about.value1_text': 'Ba ku bayanin da kuke buƙata don yanke shawara mai kyau na gida.',
        'about.value2_title': 'Gaskiya',
        'about.value2_text': 'Ingantattun bayanai game da ainihin yankunan Legas. Babu rufa-rufa.',
        'about.value3_title': 'Sauƙi',
        'about.value3_text': 'Neman gida yana da wahala. Wannan tambayar bai kamata ya zama haka ba.',
        'about.contact_title': 'Yi Magana Da Mu',
        'about.contact_text': 'Kuna da shawarwari ko kuna son yin gaisuwa? aiko mana da sako.',
        'about.contact_btn': 'Tuntuɓe Mu',
        'footer.tagline': 'Hanya mafi sauki don nemo cikakkiyar unguwarku a Legas. Tare da bayanai, gaskiya, da sauƙi.',
        'footer.explore': 'Bincika',
        'footer.company': 'Kamfani',
        'footer.connect': 'Haɗa kai',
        'footer.contact': 'Tuntuɓi',
        'footer.privacy': 'Manufar Sirri',
        'footer.built_for': 'An gina shi don Legas.',
        'review.title': 'Bayanin Masu Amfani',
        'review.share_exp': 'Faɗa Mana Labarinku',
        'review.pro_only': 'Mambobin Pro kawai za su iya barin bayani. Haɓaka don taimakawa saura!',
        'review.upgrade_btn': 'Haɓaka zuwa Pro',
        'review.your_rating': 'Kimar ku',
        'review.your_comment': 'Bayanan ku',
        'review.placeholder': 'Yaya rayuwa take a nan? Bayyana yanayin, tsaro, da sauran su...',
        'review.submitted': 'An tura bayanan ku!',
        'review.post_btn': 'Aika Bayani',
        'review.submitting': 'Ana turawa...',
        'review.loading': 'Ana loda bayanai...',
        'review.no_reviews': 'Babu bayani tukunna. Kasance na farko da zai raba ra\'ayoyinsa!',
        'auth.login_title': 'Barka da Dawowa',
        'auth.login_subtitle': 'Shin kun shirya don nemo kyakkyawar unguwarku a Legas?',
        'auth.google_btn': 'Ci gaba da Google',
        'auth.or_email': 'ko shiga tare da imel',
        'auth.email_label': 'Adireshin Imel',
        'auth.password_label': 'Kalmar Sirri',
        'auth.name_label': 'Cikakken Suna',
        'auth.login_btn': 'Shiga',
        'auth.register_title': 'Ƙirƙiri Asusun',
        'auth.register_subtitle': 'Shiga LagosFit don adana tarihin neman ku da sauran su.',
        'auth.register_btn': 'Ƙirƙiri Asusun',
        'auth.forgot_password': 'Kun manta kalmar sirri?',
        'auth.no_account': 'Ba ku da asusu?',
        'auth.register_link': 'Yi rajista a nan',
        'auth.have_account': 'Kuna da asusu tun kafin yanzu?',
        'auth.login_link': 'Shiga a maimakon haka',
        'auth.forgot_title': 'Sake Saita Kalmar Sirri',
        'auth.forgot_subtitle': 'Saka imel ɗin ku kuma za mu aika muku da link don sake saitawa.',
        'auth.reset_btn': 'Aika Link na Sake Saita',
        'auth.back_to_login': 'Koma Zuwa Shiga',
        'auth.reset_success': 'An aika link din! Duba imel din ku.',
        'auth.reset_check_email': 'Duba Imel ɗin ku',
        'auth.reset_sent_to': 'Mun aika hanyar sake saita kalmar sirri zuwa {0}.',
        'auth.reset_instruction': 'Latsa link din da ke cikin imel din don sake saita kalmar sirri.',
        'auth.reset_not_received': "Ba ku gani ba?",
        'auth.reset_spam_note': 'Duba babban babban fayil din spam naka ko',
        'auth.reset_try_again': 'sake gwadawa',
        'auth.error.user_not_found': 'Ba a sami asusu mai wannan imel ɗin ba.',
        'auth.error.wrong_password': 'Kalmar sirri ba daidai ba ce. Sake gwadawa.',
        'auth.error.invalid_credential': 'Imel ko kalmar sirri ba daidai ba ne.',
        'auth.error.too_many_requests': 'Yunkuri ya yi yawa. Da fatan za a jira.',
        'auth.error.popup_closed': 'An rufe taga ta shiga. Sake gwadawa.',
        'auth.error.network_failed': 'Matsalar hanyar sadarwa. Duba haɗin ku.',
        'auth.error.generic': 'Shiga bai yi nasara ba. Da fatan za a sake gwadawa.',
        'pricing.feat1': 'Samun damar dandamalin dukiya',
        'pricing.feat2': 'Wakilai masu tabbaci tare da nambobi',
        'pricing.feat3': 'Hukumomi masu yanar gizo da imel',
        'pricing.feat4': 'Wuraren ofis a duk fadin Legas',
        'pricing.feat5': 'TikTok na yawon gidan',
        'pricing.feat6': 'Lafiyar WhatsApp',
        'profile.title': 'Profile dinka',
        'profile.edit_btn': 'Gyara Profile',
        'profile.save_btn': 'Adana',
        'profile.saving': 'Ana adanawa...',
        'profile.cancel': 'Soke',
        'profile.name_label': 'Sunan ku',
        'profile.name_placeholder': 'Cikakken Suna',
        'profile.set_name': 'Saka sunan ku',
        'profile.updated_success': 'An sabunta profile dinka!',
        'profile.updated_fail': 'Sabuntawa ya gaza.',
        'profile.avatar_updated': 'An sabunta hoton ku!',
        'profile.avatar_optimizing': 'Ana gyara hoto...',
        'profile.avatar_saving': 'Ana adana hoto...',
        'profile.shortlist_title': 'Yankunan da Ka Zaba',
        'profile.no_favorites': 'Ba ku adana kowane yanki ba tukuna.',
        'profile.explore_btn': 'Bincika Yankuna',
        'profile.preferences': 'Saituna',
        'profile.alerts': 'Sanarwar Farashi',
        'profile.summary': 'Takaitaccen Kasuwa na Mako',
        'profile.recent_quiz': 'Idanwo aipẹ',
        'profile.view_all': 'Duba Duka',
        'profile.no_history': 'Ba a yi kowane gwaji ba tukuna.',
        'profile.take_quiz': 'Yi Gwaji',
        'profile.latest_rec': 'Nasiha ta karshe',
        'profile.review_result': 'Duba sakamako duka',
        'profile.pro_badge': 'PRO',
        'profile.upgrade_title': 'Zama Pro',
        'profile.upgrade_desc': 'Samun rahotanni, stats na tsaro, da nambobin wakilai.',
        'profile.view_pricing': 'Duba Farashi',
        'history.title': 'Tarihin Binciken Ku',
        'history.subtitle': 'Duba sakamakon gwajin ku na baya.',
        'history.no_history': 'Babu tarihi. Yi gwajin don fara bincike!',
        'history.back_to_profile': 'Koma Zuwa Profile dinka',
        'buddy.welcome': "Sannu! Ni ne Buddy, mataimakin ku na LagosFit. Na san Legas sosai. Tambaye ni game da farashin gidaje a Lekki, wuraren shakatawa a Ikeja, ko yadda zaku sami ingantattun wakilai!"
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
};
